export const allFoodsInfo = {
    ghormeSabzi: {
        id: 0,
        name: 'قرمه سبزی',
        price: 34000,
        category: 'سنتی',
        orderQuantity: 125,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/سنتی/قرمه سبزی.jpg',
    },
    gheyme: {
        id: 1,
        name: 'قیمه',
        price: 32000,
        category: 'سنتی',
        orderQuantity: 115,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/سنتی/مرغ کامل.jpg',
    },
    koobide: {
        id: 2,
        name: 'کوبیده',
        price: 40000,
        category: 'سنتی',
        orderQuantity: 128,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/سنتی/قرمه سبزی.jpg',
    },
    morgheKamel: {
        id: 3,
        name: 'مرغ کامل',
        price: 70000,
        category: 'سنتی',
        orderQuantity: 36,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/سنتی/مرغ کامل.jpg',
    },
    aashReshteh: {
        id: 4,
        name: 'آش رشته',
        price: 20000,
        category: 'سنتی',
        orderQuantity: 16,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/سنتی/قرمه سبزی.jpg',
    },
    dizi: {
        id: 5,
        name: 'دیزی',
        price: 45000,
        category: 'سنتی',
        orderQuantity: 72,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/سنتی/مرغ کامل.jpg',
    },
    maahi: {
        id: 6,
        name: 'ماهی',
        price: 90000,
        category: 'سنتی',
        orderQuantity: 14,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/سنتی/قرمه سبزی.jpg',
    },
    joojeKabab: {
        id: 7,
        name: 'جوجه کباب',
        price: 37000,
        category: 'سنتی',
        orderQuantity: 109,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/سنتی/قرمه سبزی.jpg',
    },
    pizza: {
        id: 8,
        name: 'پیتزای گوشت',
        price: 57000,
        category: 'فست فود',
        orderQuantity: 187,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/فست فود/پیتزای گوشت.jpg',
    },
    hamburger: {
        id: 9,
        name: 'همبرگر',
        price: 38000,
        category: 'فست فود',
        orderQuantity: 217,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/فست فود/پیتزای گوشت.jpg',
    },
    pasta: {
        id: 10,
        name: 'پاستا آلفردو',
        price: 42000,
        category: 'فست فود',
        orderQuantity: 66,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/فست فود/پیتزای گوشت.jpg',
    },
    wrapeMorgh: {
        id: 11,
        name: 'رپ مرغ',
        price: 24000,
        category: 'فست فود',
        orderQuantity: 52,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/فست فود/فیله سوخاری.jpg',
    },
    steak: {
        id: 12,
        name: 'استیک',
        price: 99000,
        category: 'فست فود',
        orderQuantity: 40,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/فست فود/پیتزای گوشت.jpg',
    },
    steakeMorgh: {
        id: 13,
        name: 'استیک مرغ',
        price: 45000,
        category: 'فست فود',
        orderQuantity: 51,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/فست فود/فیله سوخاری.jpg',
    },
    pirashki: {
        id: 14,
        name: 'پیراشکی',
        price: 22000,
        category: 'فست فود',
        orderQuantity: 90,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/فست فود/پیتزای گوشت.jpg',
    },
    sokhari: {
        id: 15,
        name: 'فیله سوخاری',
        price: 70000,
        category: 'فست فود',
        orderQuantity: 89,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/فست فود/فیله سوخاری.jpg',
    },
    homos: {
        id: 16,
        name: 'حمص',
        price: 18000,
        category: 'گیاهی',
        orderQuantity: 22,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/گیاهی/حمص.jpg',
    },
    taco: {
        id: 17,
        name: 'تاکو گیاهی',
        price: 16000,
        category: 'گیاهی',
        orderQuantity: 30,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/گیاهی/تاکو گیاهی.jpg',
    },
    vegeterianPizza: {
        id: 18,
        name: 'پیتزای سبزیجات',
        price: 45000,
        category: 'گیاهی',
        orderQuantity: 44,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/گیاهی/تاکو گیاهی.jpg',
    },
    pooreSibzamini: {
        id: 19,
        name: 'پوره سیب زمینی',
        price: 11000,
        category: 'گیاهی',
        orderQuantity: 9,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/گیاهی/تاکو گیاهی.jpg',
    },
    pancake: {
        id: 20,
        name: 'پنکیک کاراملی',
        price: 19000,
        category: 'گیاهی',
        orderQuantity: 61,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/گیاهی/تاکو گیاهی.jpg',
    },
    crap: {
        id: 21,
        name: 'کرپ توت فرنگی',
        price: 23000,
        category: 'گیاهی',
        orderQuantity: 32,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/گیاهی/حمص.jpg',
    },
    cake: {
        id: 22,
        name: 'کیک خامه ای',
        price: 12000,
        category: 'گیاهی',
        orderQuantity: 87,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/گیاهی/حمص.jpg',
    },
    sweet: {
        id: 23,
        name: 'شیرینی آلبالویی',
        price: 12000,
        category: 'گیاهی',
        orderQuantity: 49,
        isItInFav: false,
        isItInCart: false,
        photo: '/Images/گیاهی/حمص.jpg',
    },
}